# Generated by Django 4.0.6 on 2022-07-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=1, verbose_name=models.CharField(max_length=40)),
            preserve_default=False,
        ),
    ]
