# Generated by Django 4.0.6 on 2022-07-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_category_alter_article_author_article_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='topic',
            field=models.ManyToManyField(related_name='topic', to='blog.category'),
        ),
    ]
