# Generated by Django 4.0.6 on 2022-07-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='topic',
            field=models.ManyToManyField(related_query_name='topic_list', to='blog.category'),
        ),
    ]
