# Generated by Django 4.0.6 on 2022-07-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.CharField(max_length=13)),
                ('subject', models.CharField(max_length=40)),
                ('massage', models.TextField()),
            ],
        ),
    ]
