# Generated by Django 4.0.6 on 2022-07-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'ارتباط با ما', 'verbose_name_plural': 'ارتباطات'},
        ),
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='massage',
            field=models.TextField(verbose_name='پیغام'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='number',
            field=models.CharField(max_length=13, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='subject',
            field=models.CharField(max_length=40, verbose_name='موضوع'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='username',
            field=models.CharField(max_length=30, verbose_name='نام کاربری'),
        ),
    ]
